### ISSUE TITLE
참가자만 json에 넣기

### ISSUE THREAD

**Issue by myungwoo** [spotboard/domjudge-converter#1]
전대프연 리뷰: 참가자가 아닌 Organisation에 속한 팀도 spotboard에 표시가 되었습니다.

좀 더 구체적으로는 Team Category가 있고 Visible=true인 team category만 포함한다던지 아니면 Participant에 해당하는 팀들만 표시하든지의 기준이 필요해보입니다.

**Comment by myungwoo** [comment]
Solve by da12f51a06ac49488de944c0855c2a6bca57e6fe

**Comment by hoony9x** [comment]
오 이거.. 작년에 한양대학교 대회에서 부정행위를 했던 팀을 contest member에서 뺐다가 spotboard가 터져버려서 결국 재미없는(...) 결과 공개로 이어졌었는데 해결이 되었나 보네요.

**Comment by myungwoo** [comment]
DOMjudge API에서 public team filter를 추가했었고, 그 중에 [sortorder](/spotboard/domjudge-converter/commit/da12f51a06ac49488de944c0855c2a6bca57e6fe#diff-e22b50e740e102c8de5e858dbcd7753dR17)가 조건에 맞는 팀들만 가져옵니다.
